steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://${_BUCKET_NAME}/salesforce.key', 'salesforce.key']
- name: 'payaljain/sfdx:0.1'
  args: ['force:auth:jwt:grant', '--setdefaultusername', '-u', '${_SF_USERNAME}', '-f', './salesforce.key', '-i', '${_CONSUMER_KEY}']
- name: 'payaljain/sfdx:0.1'
  args: ['force:source:deploy', '-p', './force-app/', '--runtests', '-l', 'RunLocalTests']
substitutions:
  _BUCKET_NAME: __BUCKET_NAME__
  _SF_USERNAME: __USERNAME__
  _CONSUMER_KEY: __CONSUMER_KEY__
